# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

bengor_user_change_password:
    resource: change_password.yml

bengor_user_enable:
    resource: enable.yml

bengor_user_invite:
    resource: invite.yml

bengor_user_security:
    resource: security.yml

bengor_user_sign_up:
    resource: sign_up.yml

bengor_user_remove:
    resource: remove.yml

bengor_user_request_remember_password:
    resource: request_remember_password.yml

bengor_user_jwt:
    resource: jwt.yml
