# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

bengor_user_resend_invitation_routes:
    resource: .
    type: bengor_user_resend_invitation

bengor_user_resend_invitation_api_routes:
    resource: .
    type: bengor_user_resend_invitation_api
