# This file is part of the BenGorUserBundle bundle.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor.user_bundle.routing.security_routes_loader:
        class: BenGor\UserBundle\Routing\SecurityRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.registration_routes_loader:
        class: BenGor\UserBundle\Routing\RegistrationRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }


    bengor.user.infrastructure.mailing.swift_mailer:
        class: BenGor\User\Infrastructure\Mailing\SwiftMailer\SwiftMailerUserMailer
        arguments:
            - '@mailer'

    bengor.user.domain.event.user_registered_mailer_subscriber:
        class: BenGor\User\Domain\Event\UserRegisteredMailerSubscriber
        arguments:
            - '@bengor.user.infrastructure.mailing.swift_mailer'
            - 'prueba@prueba.com'
            - 'esto es una prueba'
        tags:
            - { name: event_subscriber, subscribes_to: BenGor\User\Domain\Model\Event\UserRegistered }

    bengor.user.domain.event_publisher:
        class: BenGor\UserBundle\EventListener\DomainEventRequestListener
        arguments:
            - ['@bengor.user.domain.event.user_registered_mailer_subscriber']
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
