# This file is part of the User bundle.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#### PERSISTENCE ####
    pdo:
        class: PDO
        arguments:
            dsn: "mysql:dbname=%database_name%"
            user: %database_user%
            password: %database_password%

    bengor.user.infrastructure.persistence.doctrine.user_repository:
        class: BenGor\User\Infrastructure\Persistence\Doctrine\DoctrineUserRepository
        arguments:
            - @doctrine.orm.entity_manager
    bengor.user.infrastructure.persistence.sql.user_repository:
        class: BenGor\User\Infrastructure\Persistence\Sql\SqlUserRepository
        arguments:
            - @pdo
    bengor.user.infrastructure.persistence.in_memory.user_repository:
        class: BenGor\User\Infrastructure\Persistence\InMemory\InMemoryUserRepository

#### SECURITY ####
    bengor.user.infrastructure.security.symfony.user_password_encoder:
        class: BenGor\User\Infrastructure\Security\Symfony\SymfonyUserPasswordEncoder
        arguments:
            - @security.password_encoder

#### APPLICATION SERVICES ####
    bengor.user.application.service.activate_user_account:
        class: BenGor\User\Application\Service\ActivateUserAccountService
        arguments:
            - @bengor.user.infrastructure.persistence.doctrine.user_repository
    bengor.user.application.service.change_user_password:
        class: BenGor\User\Application\Service\ChangeUserPasswordService
        arguments:
            - @bengor.user.infrastructure.persistence.doctrine.user_repository
            - @bengor.user.infrastructure.security.symfony.user_password_encoder
    bengor.user.application.service.change_user_password_using_remember_password_token:
        class: BenGor\User\Application\Service\ChangeUserPasswordUsingRememberPasswordTokenService
        arguments:
            - @bengor.user.infrastructure.persistence.doctrine.user_repository
            - @bengor.user.infrastructure.security.symfony.user_password_encoder
    bengor.user.application.service.log_in_user:
        class: BenGor\User\Application\Service\LogInUserService
        arguments:
            - @bengor.user.infrastructure.persistence.doctrine.user_repository
            - @bengor.user.infrastructure.security.symfony.user_password_encoder
    bengor.user.application.service.log_out_user:
            class: BenGor\User\Application\Service\LogOutUserService
            arguments:
                - @bengor.user.infrastructure.persistence.doctrine.user_repository
    bengor.user.application.service.remove_user:
        class: BenGor\User\Application\Service\RemoveUserService
        arguments:
            - @bengor.user.infrastructure.persistence.doctrine.user_repository
            - @bengor.user.infrastructure.security.symfony.user_password_encoder
    bengor.user.application.service.request_remember_password_token:
            class: BenGor\User\Application\Service\RequestRememberPasswordTokenService
            arguments:
                - @bengor.user.infrastructure.persistence.doctrine.user_repository
    bengor.user.application.service.sign_up_user:
        class: BenGor\User\Application\Service\SignUpUserService
        arguments:
            - @bengor.user.infrastructure.persistence.doctrine.user_repository
            - @bengor.user.infrastructure.security.symfony.user_password_encoder
