# This file is part of the BenGorUserBundle bundle.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor.user_bundle.event_listener.domain_event_publisher:
        class: BenGor\UserBundle\EventListener\DomainEventPublisherListener
        arguments:
            - []
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    bengor.user.domain.event.user_registered_mailer_subscriber:
        class: BenGor\User\Domain\Event\UserRegisteredMailerSubscriber
        arguments:
            - '@bengor.user.infrastructure.mailing.swift_mailer.user_mailer'
            - 'prueba@prueba.com'
            - 'esto es una prueba'
        tags:
            - { name: bengor_user_subscriber, subscribes_to: BenGor\User\Domain\Model\Event\UserRegistered }
