# This file is part of the BenGorUserBundle bundle.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor.user_bundle.event_listener.domain_event_publisher:
        class: BenGor\UserBundle\EventListener\DomainEventPublisherListener
        arguments:
            - []
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
