# This file is part of the BenGorUserBundle bundle.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor.user_bundle.routing.enable_routes_loader:
        class: BenGor\UserBundle\Routing\EnableRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.invite_routes_loader:
        class: BenGor\UserBundle\Routing\InviteRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.security_routes_loader:
        class: BenGor\UserBundle\Routing\SecurityRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.sign_up_routes_loader:
        class: BenGor\UserBundle\Routing\SignUpRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }
