# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor.user.form.type.change_password_by_request_remember_password:
        class: BenGorUser\UserBundle\Form\Type\ChangePasswordByRequestRememberPasswordType
        tags:
            - { name: form.type }

    bengor.user.form.type.change_password:
        class: BenGorUser\UserBundle\Form\Type\ChangePasswordType
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type }

    bengor.user.form.type.invite:
        class: BenGorUser\UserBundle\Form\Type\InviteType
        tags:
            - { name: form.type }

    bengor.user.form.type.remove:
        class: BenGorUser\UserBundle\Form\Type\RemoveType
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type }

    bengor.user.form.type.request_remember_password:
        class: BenGorUser\UserBundle\Form\Type\RequestRememberPasswordType
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type }

    bengor.user.form.type.sign_up_by_invitation:
        class: BenGorUser\UserBundle\Form\Type\SignUpByInvitationType
        tags:
            - { name: form.type }

    bengor.user.form.type.sign_up:
        class: BenGorUser\UserBundle\Form\Type\SignUpType
        tags:
            - { name: form.type }

    bengor.user.form.type.sign_up_with_confirmation:
        class: BenGorUser\UserBundle\Form\Type\SignUpWithConfirmationType
        tags:
            - { name: form.type }
