# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor_simple_bus.command_bus.delegates_to_message_handler_middleware:
        class: SimpleBus\Message\Handler\DelegatesToMessageHandlerMiddleware
        public: false
        arguments:
            - '@simple_bus.command_bus.command_handler_resolver'
        tags:
            - { name: bengor_user_user_command_bus_middleware, priority: -1000 }

    bengor_simple_bus.command_bus.finishes_command_before_handling_next_middleware:
        class: SimpleBus\Message\Bus\Middleware\FinishesHandlingMessageBeforeHandlingNext
        public: false
        tags:
            - { name: bengor_user_user_command_bus_middleware, priority: 1000 }

    bengor_simple_bus.doctrine_orm_bridge.collects_events_from_entities:
        class: BenGorUser\UserBundle\EventListener\CollectsEventsFromEntities
        public: false
        tags:
            # doctrine.event_subscriber tag will be added by DoctrineOrmBridgeExtension
            - { name: event_recorder }
            - { name: doctrine.event_subscriber }

    bengor_simple_bus.doctrine_transactional:
        class: SimpleBus\DoctrineORMBridge\MessageBus\WrapsMessageHandlingInTransaction
        arguments:
            - '@doctrine'
            - 'default'
        tags:
            - { name: bengor_user_user_command_bus_middleware, priority: 0 }

    bengor_simple_bus.handles_recoded_messages:
        class: SimpleBus\Message\Recorder\HandlesRecordedMessagesMiddleware
        arguments:
            - '@bengor_simple_bus.doctrine_orm_bridge.collects_events_from_entities'
            - '@event_bus'
        tags:
            - { name: bengor_user_user_command_bus_middleware, priority: -100 }

