# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#### Url generator ####
    bengor.user.infrastructure.routing.symfony_url_generator:
        class: BenGorUser\User\Infrastructure\Routing\Symfony\SymfonyUserUrlGenerator
        arguments:
            - '@router'
    bengor_user.symfony_url_generator:
        alias: bengor.user.infrastructure.routing.symfony_url_generator

#### Route loader ####
    bengor.user_bundle.routing.change_password_routes_loader:
        class: BenGorUser\UserBundle\Routing\ChangePasswordRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.enable_routes_loader:
        class: BenGorUser\UserBundle\Routing\EnableRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.invite_routes_loader:
        class: BenGorUser\UserBundle\Routing\InviteRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.security_routes_loader:
        class: BenGorUser\UserBundle\Routing\SecurityRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.sign_up_routes_loader:
        class: BenGorUser\UserBundle\Routing\SignUpRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.remove_routes_loader:
        class: BenGorUser\UserBundle\Routing\RemoveRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.request_remember_password_routes_loader:
        class: BenGorUser\UserBundle\Routing\RequestRememberPasswordRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }
