# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor.user_bundle.routing.change_password_routes_loader:
        class: BenGorUser\UserBundle\Routing\ChangePasswordRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.enable_routes_loader:
        class: BenGorUser\UserBundle\Routing\EnableRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.invite_routes_loader:
        class: BenGorUser\UserBundle\Routing\InviteRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.remove_routes_loader:
        class: BenGorUser\UserBundle\Routing\RemoveRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.request_remember_password_routes_loader:
        class: BenGorUser\UserBundle\Routing\RequestRememberPasswordRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.resend_invitation_routes_loader:
        class: BenGorUser\UserBundle\Routing\ResendInvitationRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }


    bengor.user_bundle.routing.security_routes_loader:
        class: BenGorUser\UserBundle\Routing\SecurityRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.sign_up_routes_loader:
        class: BenGorUser\UserBundle\Routing\SignUpRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

### API
    bengor.user_bundle.routing.api_change_password_routes_loader:
        class: BenGorUser\UserBundle\Routing\Api\ChangePasswordRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.api_enable_routes_loader:
        class: BenGorUser\UserBundle\Routing\Api\EnableRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.api_invite_routes_loader:
        class: BenGorUser\UserBundle\Routing\Api\InviteRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.api_jwt_routes_loader:
        class: BenGorUser\UserBundle\Routing\Api\JwtRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.api_remove_routes_loader:
        class: BenGorUser\UserBundle\Routing\Api\RemoveRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.api_request_remember_password_routes_loader:
        class: BenGorUser\UserBundle\Routing\Api\RequestRememberPasswordRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.api_resend_invitation_routes_loader:
        class: BenGorUser\UserBundle\Routing\Api\ResendInvitationRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.user_bundle.routing.api_sign_up_routes_loader:
        class: BenGorUser\UserBundle\Routing\Api\SignUpRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }
